package com.hansck.shadowingulite.database

/**
 * Created by Hans CK on 13-Jun-18.
 */
enum class QueryEnum {

	INSERT_UPDATE_USER, INSERT_AVATARS, INSERT_LESSONS, INSERT_BADGES, INSERT_TITLES, INSERT_WORDS,
	UPDATE_USER, BUY_AVATAR, UPDATE_LESSONS, UPDATE_BADGE, UPDATE_TITLE,
	GET_USERS, GET_AVATARS, GET_LESSONS, GET_BADGES, GET_TITLES, GET_WORDS, GET_LEVELS
}